#!/usr/bin/env python3

import os
import subprocess
from argparse import ArgumentParser
from multiprocessing import Pool


def run_fast_relax(
    *,
    base_dir: str,
    pdb_chain: str,
    variant: str,
    rosetta_bin: str,
    skip_if_exists: bool,
):
    # make Rosetta single-threaded per process to avoid oversubscription
    os.environ.setdefault("OMP_NUM_THREADS", "1")

    # create and change to necessary directory
    chain_dir = os.path.join(base_dir, pdb_chain)
    if not os.path.exists(chain_dir):
        os.mkdir(chain_dir)
        print("Created directory:", chain_dir)

    os.chdir(chain_dir)
    print("Changed to", chain_dir)

    # create a resfile
    variant_resfile = pdb_chain + "_" + variant + ".resfile"
    with open(variant_resfile, "wt") as opf:
        opf.write("NATAA\n")
        opf.write("start\n")
        opf.write(variant[1:-1] + " " + pdb_chain[-1] + " PIKAA " + variant[-1])

    # print whatever it printed
    print(f"Variant: {variant[1:-1]}, {variant[-1]}")
    print(f"pdb_chain: {pdb_chain}, {pdb_chain[-1]}")

    # rosetta_cmd
    start_struct = os.path.join(base_dir, pdb_chain, pdb_chain + "_relaxed.pdb")

    print("=" * 40)
    print("=" * 40)
    print(f"Start struct: {start_struct}")
    print("=" * 40)
    print("=" * 40)

    # check if there is already a relaxed structure for this variant
    relaxed_struct_path = os.path.join(chain_dir, f"{pdb_chain}_relaxed_{variant}_relaxed.pdb")
    if os.path.exists(relaxed_struct_path):
        print(
            f"Relaxed structure for {variant} already exists at {relaxed_struct_path}."
        )
        if skip_if_exists:
            print("Skipping FastRelax for this variant.")
            print("If you want to rerun, set skip_if_exists to False.")
            return
    else:
        print(f"No existing relaxed structure for {variant}. Running FastRelax.")

    rosetta_relax_cmd = [
            rosetta_bin,
            "-in:file:s",
            start_struct,
            "-in:file:fullatom",
            "-relax:constrain_relax_to_start_coords",
            "-out:no_nstruct_label",
            "-relax:ramp_constraints false",
            "-relax:respect_resfile",
            "-packing:resfile",
            variant_resfile,
            "-default_max_cycles",
            "200",
            "-out:file:scorefile",
            os.path.join(chain_dir, pdb_chain + "_relaxed.sc"),
            "-out:suffix",
            "_" + variant + "_relaxed",
        ]


    # run Rosetta FastRelax
    # os.system(rosetta_relax_cmd)
    subprocess.run(
        rosetta_relax_cmd,
        check=True,
        stdout=subprocess.DEVNULL,  # toss stdout
        stderr=subprocess.DEVNULL,
    )  # toss stderr


def main():
    """
    This is a utility script created to work with the ThermoNet ddG prediction protocol.
    It takes a given list of variants and the path to the Rosetta binary. It runs the
    Rosetta binary to create a structural model for each of the variant in the list.
    """
    # parse command-line arguments
    parser = ArgumentParser(
        description="""This is a utility script created to work with the ThermoNet ddG prediction protocol.
        It takes a given list of variants and the path to the Rosetta binary. It runs the
        Rosetta binary to create a structural model for each of the variant in the list."""
    )
    parser.add_argument(
        "-l",
        "--variant-list",
        dest="variant_list",
        type=str,
        required=True,
        help='A list of variants, one per line in the format "PDB CHAIN POS WT MUT"',
    )
    # parser.add_argument('-s', '--start-struct', dest='start_struct', type=str,
    #        required=True, help='PDB file of the starting structure.')
    parser.add_argument(
        "--rosetta-bin",
        dest="rosetta_bin",
        type=str,
        required=True,
        help="Rosetta FastRelax binary executable.",
    )
    parser.add_argument(
        "--base-dir",
        dest="base_dir",
        type=str,
        required=True,
        help="The base directory to store all data generated by this script.",
    )
    parser.add_argument(
        "--num-cpus",
        dest="num_cpus",
        type=int,
        required=False,
        default=1,
        help="Maximum number of concurrent Rosetta jobs (default: 1)",
    )
    parser.add_argument(
        "--rerun",
        dest="rerun",
        action="store_true",
        help="If set, rerun FastRelax even if output files already exist.",
    )
    args = parser.parse_args()

    # parse all the variants into a list
    variants = []
    with open(args.variant_list, "rt") as ipf:
        for l in ipf:
            pdb_chain, pos, w, m = l.strip().split()
            variants.append((pdb_chain, w + pos + m))

    # create relevant directories and input files for submitting slurm jobs
    # for each pair of wild-type and variant
    base_dir = os.path.abspath(args.base_dir)

    chain_dir = os.path.join(base_dir, pdb_chain)
    if not os.path.exists(chain_dir):
        os.mkdir(chain_dir)
        print("Created directory:", chain_dir)
    else:
        print("Directory already exists:", chain_dir)

    with Pool(processes=args.num_cpus) as pool:
        results = []
        for pdb_chain, variant in variants:
            result = pool.apply_async(
                run_fast_relax,
                kwds={
                    "base_dir": base_dir,
                    "pdb_chain": pdb_chain,
                    "variant": variant,
                    "rosetta_bin": args.rosetta_bin,
                    "skip_if_exists": not args.rerun,
                },
            )
            results.append(result)

        # Wait for all tasks to complete
        for result in results:
            result.get()

    #
    # for pdb_chain, variant in variants:
    #     # create and change to necessary directory
    #     chain_dir = os.path.join(base_dir, pdb_chain)
    #     if not os.path.exists(chain_dir):
    #         os.mkdir(chain_dir)
    #         print('Created directory:', chain_dir)
    #
    #     os.chdir(chain_dir)
    #     print('Changed to', chain_dir)
    #
    #     # create a resfile
    #     variant_resfile = pdb_chain + '_' + variant + '.resfile'
    #     with open(variant_resfile, 'wt') as opf:
    #         opf.write('NATAA\n')
    #         opf.write('start\n')
    #         opf.write(variant[1:-1] + ' ' + pdb_chain[-1] + ' PIKAA ' + variant[-1])
    #
    #
    #     # print whatever it printed
    #     print(
    #         f"Variant: {variant[1:-1]}, {variant[-1]}"
    #     )
    #     print(
    #         f"pdb_chain: {pdb_chain}, {pdb_chain[-1]}"
    #     )
    #
    #
    #     # rosetta_cmd
    #     start_struct = os.path.join(base_dir, pdb_chain, pdb_chain + '_relaxed.pdb')
    #
    #     print("=" * 40)
    #     print("=" * 40)
    #     print(f"Start struct: {start_struct}")
    #     print("=" * 40)
    #     print("=" * 40)
    #     rosetta_relax_cmd = ' '.join([args.rosetta_bin,
    #         '-in:file:s', start_struct, '-in:file:fullatom',
    #         '-relax:constrain_relax_to_start_coords',
    #         '-out:no_nstruct_label', '-relax:ramp_constraints false',
    #         '-relax:respect_resfile',
    #         '-packing:resfile', variant_resfile,
    #         '-default_max_cycles', '200',
    #         '-out:file:scorefile', os.path.join(chain_dir, pdb_chain + '_relaxed.sc'),
    #         '-out:suffix', '_' + variant + '_relaxed'
    #     ])
    #
    #     # run Rosetta FastRelax
    #     os.system(rosetta_relax_cmd)
    #
    #     raise NotImplementedError()


if __name__ == "__main__":
    main()
